config/routes.rb
Rails.application.routes.draw do
  resources :siteblogs
  get 'site/index'
 root 'site#index'

 get '/overview', :to => 'site#overview'
 get 'floorplan', :to => 'site#floorplan'
 get 'testimonial', :to => 'site#testimonial'
 get '/blog', :to => 'site#blog'
 get '/blog/:id', :to => 'site#blog_detail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/siteblog.rb
class Siteblog < ApplicationRecord
	has_attached_file :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'

  def index
  end

  def blog
  	@siteblog = Siteblog.where(:status => true)
  end

  def blog_detail
  	@siteblog = Siteblog.find(params[:id])
  end

end

app/controllers/siteblogs_controller.rb
class SiteblogsController < ApplicationController
  before_action :set_siteblog, only: [:show, :edit, :update, :destroy]

  # GET /siteblogs
  # GET /siteblogs.json
  def index
    @siteblogs = Siteblog.all
  end

  # GET /siteblogs/1
  # GET /siteblogs/1.json
  def show
  end

  # GET /siteblogs/new
  def new
    @siteblog = Siteblog.new
  end

  # GET /siteblogs/1/edit
  def edit
  end

  # POST /siteblogs
  # POST /siteblogs.json
  def create
    @siteblog = Siteblog.new(siteblog_params)

    respond_to do |format|
      if @siteblog.save
        format.html { redirect_to @siteblog, notice: 'Siteblog was successfully created.' }
        format.json { render :show, status: :created, location: @siteblog }
      else
        format.html { render :new }
        format.json { render json: @siteblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /siteblogs/1
  # PATCH/PUT /siteblogs/1.json
  def update
    respond_to do |format|
      if @siteblog.update(siteblog_params)
        format.html { redirect_to @siteblog, notice: 'Siteblog was successfully updated.' }
        format.json { render :show, status: :ok, location: @siteblog }
      else
        format.html { render :edit }
        format.json { render json: @siteblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /siteblogs/1
  # DELETE /siteblogs/1.json
  def destroy
    @siteblog.destroy
    respond_to do |format|
      format.html { redirect_to siteblogs_url, notice: 'Siteblog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_siteblog
      @siteblog = Siteblog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def siteblog_params
      params.require(:siteblog).permit(:title, :desc, :longdesc, :status, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
	def url_index
		"/"
	end

	def url_overview
		"/overview"
	end

	def url_floorplan
		"/floorplan"
	end

	def url_testimonial
		"/testimonial"
	end

	def url_blog
		"/blog"
	end

	def url_blog_detail(id)
		"/blog/#{id}"
	end
end

app/helpers/siteblogs_helper.rb
module SiteblogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @metatitle %></title>
    <meta content="<%= @metadescription %>" name="description">
    <meta content="<%= @metakeywords %>" name="keyword">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="/site/css/style.css">
   
  </head>
  <body>
	  <div class="headerwrapper">
	  	<div class="text-left logo"></div>
	  	<div class="text-left navbar">
	  		<ul>
	  			<li><a href="<%= url_index %>">Home</a></li>
	  			<li><a href="<%= url_overview %>">Overview</a></li>
	  			<li><a href="<%= url_floorplan %>">Floor Plan</a></li>
	  			<li><a href="<%= url_testimonial %>">Testimonial</a></li>
	  			<li><a href="<%= url_blog %>">Blogs</a></li>
	  		</ul>
	  	</div>
	  </div>
  <%= yield %>
  
 <div class="container">
 	<div class="footer text-center">
 		Copyrights @ Supriya.Barkund 2017
 	</div>
 </div>
  
  </body>
</html>

app/views/site/blog.html.erb
<section>
	<div class="container pdnt100">
		<h1>Blog Page</h1>	
		<% @siteblog.each do | siteblog | %>
			<img src="<%= siteblog.image.url %>" width=100 height=100 /><br><br>
			<a href="<%= url_blog_detail(siteblog.id) %>"><%= siteblog.title %></a><br><br>
			<%= siteblog.desc %><br><br>
		<% end %>
	</div>
</section>

app/views/site/blog_detail.html.erb
<section>
	<div class="container pdnt100">
		<h1>Blog listing</h1>	
		
			
			<%= @siteblog.title %></a><br><br>
			<%= @siteblog.longdesc %><br><br>
		
	</div>
</section>

app/views/site/floorplan.html.erb
<section>
	<div class="container pdnt100">
		<h1>Floor Plan Page</h1>		
	</div>
</section>

app/views/site/index.html.erb
<section>
	<div class="container pdnt100">
		<h1>Index Page</h1>		
	</div>
</section>

app/views/site/overview.html.erb
<section>
	<div class="container pdnt100">
		<h1>Overview Page</h1>		
	</div>
</section>

app/views/site/testimonial.html.erb
<section>
	<div class="container pdnt100">
		<h1>Testimoail Page</h1>		
	</div>
</section>

app/views/siteblogs/_form.html.erb
<%= form_for @siteblog, :html => { :multipart=> true } do |f| %>
  <% if @siteblog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@siteblog.errors.count, "error") %> prohibited this siteblog from being saved:</h2>

      <ul>
      <% @siteblog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :longdesc %>
    <%= f.text_area :longdesc %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :Image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/siteblogs/edit.html.erb
<h1>Editing Siteblog</h1>

<%= render 'form', siteblog: @siteblog %>

<%= link_to 'Show', @siteblog %> |
<%= link_to 'Back', siteblogs_path %>

app/views/siteblogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Siteblogs</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Desc</th>
      <th>Longdesc</th>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @siteblogs.each do |siteblog| %>
      <tr>
        <td><img src="<%= siteblog.image.url %>" width=100 height=100 /></td>
        <td><%= siteblog.title %></td>
        <td><%= siteblog.desc %></td>
        <td><%= siteblog.longdesc %></td>
        <td><%= siteblog.status %></td>
        <td><%= siteblog.date %></td>
        <td><%= link_to 'Show', siteblog %></td>
        <td><%= link_to 'Edit', edit_siteblog_path(siteblog) %></td>
        <td><%= link_to 'Destroy', siteblog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Siteblog', new_siteblog_path %>

app/views/siteblogs/new.html.erb
<h1>New Siteblog</h1>

<%= render 'form', siteblog: @siteblog %>

<%= link_to 'Back', siteblogs_path %>

app/views/siteblogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @siteblog.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @siteblog.desc %>
</p>

<p>
  <strong>Longdesc:</strong>
  <%= @siteblog.longdesc %>
</p>

<p>
  <strong>Status:</strong>
  <%= @siteblog.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @siteblog.date %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= @siteblog.image %>" width=100 height=100 />
</p> 

<%= link_to 'Edit', edit_siteblog_path(@siteblog) %> |
<%= link_to 'Back', siteblogs_path %>